version: '3'

services:

  db: 
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_django_crud:/var/lib/postgresql/data

  web:
    build: .
    tty: true
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  postgres_django_crud: